steps:
  deploy:
    image: appleboy/ssh
    settings:
      host: 82.29.153.167
      username: root
      key:
        from_secret: ssh_key
      script:
        - cd /home/BudgetBridge
        - git pull origin main
        - sudo systemctl restart BudgetBridge.service
